FROM nginx:alpine

COPY index.html /usr/share/nginx/html/index.html

# Script de entrypoint que injeta a variável BACKEND_URL no HTML em runtime
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 80

ENTRYPOINT ["/entrypoint.sh"]